# サブレディット設定

# 技術関連
tech = [
    "StableDiffusion",
    "artificial",
    "ClaudeAI",
    "OpenAI",
    "GoogleGemini",
    "cursor",
    "MachineLearning",
    "LocalLLaMA",
    "singularity",
    "AgentGPT",
    "AutoGPT",
]

# ニュース
news = [
    "technology",
    "Futurology",
]
