name: Workflow Telemetry

on:
  workflow_run:
    workflows: ["JS Tests", "Python Tests"]
    types: [completed]

permissions:
  contents: read

jobs:
  telemetry:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
